name: pages
on: [push]
jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm i esbuild
      - run: npm run build -- --minify
      - run: rm -r src node_modules .gitignore package-lock.json tsconfig.json package.json
      - uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages
          folder: .
